app.constraints.payment-cards.max-count=5

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/PaycardSystem}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog/changelog-master.xml
spring.liquibase.drop-first=false

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/PaycardSystem

keycloak.auth-server-url=http://localhost:8180
keycloak.realm=PaycardSystem
keycloak.resource=paycard-system-api
keycloak.credentials.secret=CHATdho1reWyaSQAUCuJ4vGCO4a6UIUe